create table if not exists public.visitors (
    id bigint generated by default as identity primary key,
    page text not null default '/',
    visited_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    customer_email text,
    package_type text not null default 'باقة مخصصة',
    details text not null default '',
    budget numeric,
    status text not null default 'new' check (status in ('new', 'contacted', 'completed', 'cancelled')),
    created_at timestamptz not null default now()
);

alter table public.visitors enable row level security;
alter table public.orders enable row level security;

drop policy if exists "public can record visits" on public.visitors;
create policy "public can record visits"
on public.visitors for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read visits" on public.visitors;
create policy "owner can read visits"
on public.visitors for select
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read orders" on public.orders;
create policy "owner can read orders"
on public.orders for select
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

drop policy if exists "owner can update orders" on public.orders;
create policy "owner can update orders"
on public.orders for update
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

create table if not exists public.site_content (
    id bigint generated by default as identity primary key,
    content_type text not null check (content_type in ('setting', 'skill', 'portfolio', 'video', 'package', 'review')),
    title text not null,
    description text not null default '',
    category text not null default '',
    image_url text not null default '',
    icon text not null default '',
    rating smallint check (rating between 1 and 5),
    sort_order integer not null default 0,
    is_visible boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "public can read visible site content" on public.site_content;
create policy "public can read visible site content"
on public.site_content for select
to anon, authenticated
using (is_visible = true or (auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

drop policy if exists "owner can insert site content" on public.site_content;
create policy "owner can insert site content"
on public.site_content for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

drop policy if exists "owner can update site content" on public.site_content;
create policy "owner can update site content"
on public.site_content for update
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

drop policy if exists "owner can delete site content" on public.site_content;
create policy "owner can delete site content"
on public.site_content for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');
